export const MARKET_SECTORS = {
  TECH: ["AAPL", "MSFT", "NVDA", "GOOGL", "META", "AVGO", "ORCL", "CRM"],
  FINANCE: ["JPM", "BAC", "WFC", "GS", "MS", "V", "MA", "PYPL"],
  CRYPTO: ["BTC-USD", "ETH-USD", "SOL-USD", "BNB-USD", "ADA-USD", "XRP-USD"],
  ENERGY: ["XOM", "CVX", "SHEL", "BP", "TTE", "COP"],
  HEALTHCARE: ["LLY", "UNH", "JNJ", "ABBV", "MRK", "PFE"],
  CONSUMER: ["AMZN", "WMT", "COST", "HD", "PG", "KO", "PEP"],
  INDICES: ["^GSPC", "^NDX", "^DJI", "^RUT"],
  NEW_PICKS: ["DHI", "CISS", "LRCX", "NVDA", "HNGE", "TSM", "FIG", "BLSH", "GEMI", "FIGR", "KLAR", "VIA", "STUB", "PTRN", "FRMI", "META", "MSFT", "SLV", "NAVN", "NOK", "GLOO", "RAMP", "DRI", "AVAV", "AVGO", "RTX", "GPUS", "NFLX", "CINT", "TOO"]
};

export const ALL_SYMBOLS = Object.values(MARKET_SECTORS).flat();

// Map of symbols to human-readable names for UI display
export const SYMBOL_NAMES: Record<string, string> = {
  "DHI": "D.R. Horton",
  "CISS": "Cisner",
  "LRCX": "Lam Research",
  "HNGE": "Henge",
  "TSM": "TSMC",
  "FIG": "Fortress",
  "BLSH": "Blush",
  "GEMI": "Gemini",
  "FIGR": "Figur",
  "KLAR": "Klar",
  "VIA": "Via",
  "STUB": "Stub",
  "PTRN": "Pattern",
  "FRMI": "Fermi",
  "SLV": "Silver Trust",
  "NAVN": "Navient",
  "NOK": "Nokia",
  "GLOO": "Gloo",
  "RAMP": "LiveRamp",
  "DRI": "Darden Restaurants",
  "AVAV": "AeroVironment",
  "RTX": "RTX Corp",
  "GPUS": "GPUs",
  "NFLX": "Netflix",
  "CINT": "Cintas",
  "TOO": "Teekay Offshore",
  "AAPL": "Apple",
  "MSFT": "Microsoft",
  "NVDA": "NVIDIA",
  "GOOGL": "Google",
  "META": "Meta",
  "AVGO": "Broadcom",
  "ORCL": "Oracle",
  "CRM": "Salesforce",
  "JPM": "JPMorgan",
  "BAC": "Bank of America",
  "WFC": "Wells Fargo",
  "GS": "Goldman Sachs",
  "MS": "Morgan Stanley",
  "V": "Visa",
  "MA": "Mastercard",
  "PYPL": "PayPal",
  "BTC-USD": "Bitcoin",
  "ETH-USD": "Ethereum",
  "SOL-USD": "Solana",
  "BNB-USD": "Binance Coin",
  "ADA-USD": "Cardano",
  "XRP-USD": "Ripple",
  "XOM": "ExxonMobil",
  "CVX": "Chevron",
  "SHEL": "Shell",
  "BP": "BP",
  "TTE": "TotalEnergies",
  "COP": "ConocoPhillips",
  "LLY": "Eli Lilly",
  "UNH": "UnitedHealth",
  "JNJ": "Johnson & Johnson",
  "ABBV": "AbbVie",
  "MRK": "Merck",
  "PFE": "Pfizer",
  "AMZN": "Amazon",
  "WMT": "Walmart",
  "COST": "Costco",
  "HD": "Home Depot",
  "PG": "Procter & Gamble",
  "KO": "Coca-Cola",
  "PEP": "PepsiCo",
  "^GSPC": "S&P 500",
  "^NDX": "Nasdaq 100",
  "^DJI": "Dow Jones",
  "^RUT": "Russell 2000"
};

export const POPULAR_SYMBOLS = ALL_SYMBOLS.map(symbol => ({
  label: SYMBOL_NAMES[symbol] || symbol,
  value: symbol
}));
